apiVersion: apps/v1
kind: Deployment
metadata:
  name: "java-app"
  namespace: ms
  labels:
    app: "java-app"
spec:
  selector:
    matchLabels:
      app: "java-app"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "java-app"
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: "java-app"
        image:  naresh2603/java:v1
        ports:
        - containerPort:  8080
          name: "java-app"
---
apiVersion: v1
kind: Service
metadata:
  name: "java-app"
  namespace: ms
spec:
  selector:
    app: "java-app"
  type: NodePort
  ports:
  - name: "java-app"
    port: 8080
    targetPort: 8080
